### ISSUE TITLE
Exdate lists are not comma-separated

### ISSUE THREAD

**Issue by monomon** [robur-coop/icalendar#9]
Exdates must be comma separated
https://www.kanzaki.com/docs/ical/exdate.html

I am testing now with an exception list and I get this:
`EXDATE:20240517T000000Z20240520T000000Z20240619T000000Z20240621T000000Z`

I'll try to fix it myself to get some Ocaml experience. Also I see there are no serialization tests. I should try to add some.

**Comment by monomon** [comment]
I have a fix, will clean up and submit.

**Comment by monomon** [comment]
#10 Is the suggested fix.

**Comment by hannesm** [comment]
Thanks for your fix in #10.
